module.exports = {
    leaderboardCooldown: new Set(),
    tempInvitees: [],
    naughtyList: {},
    codeUses: new Map(),
    tempBlackjackData: {},
    tempBlacksmithData: {},
    tempInfiltrateData: {},
    tempRoyaleData: {},
    tempTrialData: {},
    tempRaidData: {},
    tempRouletteData: {},
    tempRouletteGame: {},
    tempRoyaleGame: {},
    blackjackCooldown: new Set(),
    blacksmithCooldown: new Set(),
    infiltrateCooldown: new Set(),
    raidCooldown: new Set(),
    trialCooldown: new Set(),
}
